import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider";
import React from "react";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="max-w-[1600px] mx-auto px-12">
                <Header/>
                <div className="grid grid-cols-12 gap-4">
                    <Sidebar/>
                    {children}
                </div>
            </div>

        </ThemeProvider>
        </body>
        </html>
    )
}
